name: Automated Test
on: [push]

jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      
    - name: Run the test input files
      run:
        python3 find_lowest_number.py test_data/test1_input.txt test1_results.txt
        diff test1_results.txt test_data/test1_expected.txt

        python3 find_lowest_number.py test_data/test2_input.txt test2_results.txt
        diff test1_results.txt test_data/test2_expected.txt

        python3 find_lowest_number.py test_data/test3_input.txt test3_results.txt
        diff test3_results.txt test_data/test3_expected.txt
